### ISSUE TITLE
BiomedParseData ?

### ISSUE THREAD

**Issue by vatsal1-research** [microsoft/BiomedParse#18]
Great work by the authors for open sourcing this part of the project, really aspiring!, we look forward to test such models at inference stage recreating the published metrics, setting up the stage towards utilizing in everyday work.

It would be more great if the dataset mentioned in a the paper "BiomedParseData can be accessed at https://aka.ms/biomedparse-release" could also be alternatively accessed via hugging face.

**Comment by theodore-zhao** [comment]
Please check out our dataset on HuggingFace here: https://huggingface.co/datasets/microsoft/BiomedParseData

**Comment by Heodel** [comment]
Hello, your work is a great contribution to the community. I noticed that only part of the data is open-sourced, such as ISIC-2018 and AMOS2022 processed datasets, but I couldn't find them. Could you please let me know where I can access these processed datasets? Thank you!

**Comment by Heodel** [comment]
@theodore-zhao

**Comment by theodore-zhao** [comment]
Please find the datasets here: https://huggingface.co/datasets/microsoft/BiomedParseData We are adding more to this repo. Amos2022 is currently there. Thanks!
