### ISSUE TITLE
Question on finetuning

### ISSUE THREAD

**Issue by hpichlerbio** [microsoft/BiomedParse#20]
Thanks for the great work!

I am really interested in finetuning this on my own data, but I am not quite sure, if it is possible.
Can I also finetune the model on instance segmentation data? Semantic segmentation is not possible in my case. 
If not, do you have any recommendations on foundation models capable of doing instance segmentation without having to add an adapter to the model?

Thank you in advance!

**Comment by theodore-zhao** [comment]
Thanks for the feedback! The model currently output semantic segmentation only. I will add a postprocessing script on the output to turn it into instance segmentation. Then you can finetune on semantic mask and post process to instance outputs.

**Comment by hpichlerbio** [comment]
> Thanks for the feedback! The model currently output semantic segmentation only. I will add a postprocessing script on the output to turn it into instance segmentation. Then you can finetune on semantic mask and post process to instance outputs.

Thanks, that would be amazing!

**Comment by evanrubel** [comment]
Out of curiosity, is the post-processing very involved? Or does the model provide some kind of raw output to identify different instances?

**Comment by theodore-zhao** [comment]
The postprocessing is a simple off the shelf tool to partition the semantic output into non-overlapping instance sub regions. Yes. the model doesn't output instances related information.

**Comment by theodore-zhao** [comment]
A pathology instance inference example is just provided in inference_examples_RGB.ipynb. There is a simple code for post-processing the semantic output. Hope that works for you!

**Comment by hpichlerbio** [comment]
Thanks, I will look into that :)
