### ISSUE TITLE
Add object type 'injury' for finetuning

### ISSUE THREAD

**Issue by macromeer** [microsoft/BiomedParse#29]
I intend to detect injury regions in pathological images (example: AFOG staining of cardiac tissue) and I would like to finetune the pretrained model accordingly. As BiomedParse has been trained on similar object types, I was hoping that this is feasible. Without having gone too deep into your codebase, I was wondering what you'd suggest. Thanks for your great work.

**Comment by theodore-zhao** [comment]
We didn't have injury segmentation examples for pretraining, but you can finetune on your own dataset. What you need is some images with ground truth masks for the injury region. Then you can prepare the data in the way described in README. Curious to learn how that works for you!

**Comment by macromeer** [comment]
That I have already prepared. I only ran into problems upon training that appeared to be related to object types. I had added ‘injury’ to the labels json in the dataset folder and mask filenames, but as training terminated I concluded that changes need to be applied also elsewhere in the code, no?

**Comment by theodore-zhao** [comment]
I see. In the dataset json file, please refer to injury object type in the text prompt. You can use "injury regions in pathological images
" or something for the model to relate to it's pretraining. The class for this could be "lesion", "id": 12. Hope this solves the problem for you.

**Comment by macromeer** [comment]
Thank you for this suggestion. I tried something similar. But apparently I have an unrelated issue, because the error that I get when executing `bash ./assets/scripts/train.sh` also appears with the demo dataset. So something seems to be messed up in my env.

Error message excerpt:
```
  File "/opt/miniforge3/envs/biomedparse/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64331,1],0]
  Exit code:    1
```

**Comment by theodore-zhao** [comment]
Can you check if the json file is correct? Sometimes it happens when git cloning the repo that the json file gets deprecated. If that happens you can use a small dataset from https://huggingface.co/datasets/microsoft/BiomedParseData as reference.

**Comment by macromeer** [comment]
Yes, I did. Can you see something wrong in the generated test.json?


[test.json](https://github.com/user-attachments/files/17927297/test.json)

**Comment by macromeer** [comment]
Finetuning in progress...

![Image](https://github.com/user-attachments/assets/070dbf6f-5c63-4a38-95d3-55c42b6ae2fa)
