### ISSUE TITLE
Potential Bug in Image Resizing for interactive_infer_image

### ISSUE THREAD

**Issue by MohammedSB** [microsoft/BiomedParse#31]
Hi,

Two potentials bugs at `/scratch/ssd004/datasets/med-img-data/mohammed/BiomedParse/inference_utils/inference.py`.

1:
https://github.com/microsoft/BiomedParse/blob/6f731d0a6ebf3d3f3ad1c2db9cf26d405f595984/inference_utils/inference.py#L22
The line above only resizes one of the dimensions. If you start with an image with shape (1080, 1240, 3) and apply the above transformation, you will end up with (1024, 1175, 3). Instead, it should be changed to ` t.append(transforms.Resize((1024, 1024), interpolation=Image.BICUBIC))`

2:
https://github.com/microsoft/BiomedParse/blob/6f731d0a6ebf3d3f3ad1c2db9cf26d405f595984/inference_utils/inference.py#L74-L78
in the above, the goal is to resize to the original size. But `data['height']` and `data['width']` does not save the original size.

https://github.com/microsoft/BiomedParse/blob/6f731d0a6ebf3d3f3ad1c2db9cf26d405f595984/inference_utils/inference.py#L40-L47
They are storing the image size after resizing.

**Comment by theodore-zhao** [comment]
Thanks for identifying the issue! We have fixed the image resizing problem. The issue was hidden because all the image file loading utils functions was doing resizing beforehand, so the corner cases were all overwritten by the desired size.
