### ISSUE TITLE
Assistance Needed with example_prediction.py

### ISSUE THREAD

**Issue by FrancoisPorcher** [microsoft/BiomedParse#32]
Hi

I’m encountering an issue while trying to run the `example_prediction.py` file. Could you please clarify the exact command you use to execute it?

Here are the commands I’ve tried so far, but none of them worked:

`mpiexec example_prediction.py`
`torch run example_prediction.py`
`torch.distributed run example_prediction.py`

The error originates from the following line in `utilities/distributed.py (line 7)`:

`from mpi4py import MPI`

Could you provide guidance on resolving this error?

Thank you for your assistance!

**Comment by Adibvafa** [comment]
@FrancoisPorcher Are you setting up a new conda enviornment for it?

**Comment by Adibvafa** [comment]
> > [@FrancoisPorcher](https://github.com/FrancoisPorcher) Are you setting up a new conda enviornment for it?
> 
> Yes I am I just reproduced the environment from the authors (with mamba and not conda though)

You should follow the exact steps and setup a new conda environment otherwise you will run into issue.

**Comment by jlgs96** [comment]
Hi there, i just encounter a problem, i ve just installed everything and working but when i execute example_prediciton.py it throws me this next error:
Traceback (most recent call last):
  File "/home/jolurobolab/Documentos/develop/DPCDM/BiomedParse/example_prediction.py", line 10, in <module>
    from inference_utils.inference import interactive_infer_image
  File "/home/jolurobolab/Documentos/develop/DPCDM/BiomedParse/inference_utils/inference.py", line 34, in <module>
    from .output_processing import mask_stats, combine_masks
  File "/home/jolurobolab/Documentos/develop/DPCDM/BiomedParse/inference_utils/output_processing.py", line 6, in <module>
    target_dist = json.load(open("inference_utils/target_dist.json"))
  File "/home/jolurobolab/anaconda3/envs/biomedparse/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/jolurobolab/anaconda3/envs/biomedparse/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/jolurobolab/anaconda3/envs/biomedparse/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jolurobolab/anaconda3/envs/biomedparse/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I can not encounter the reason for it, anyone here found the same problem?

**Comment by jlgs96** [comment]
It seems the reason of the error was that in inference_utils/target_dist.json was ready to make a git lfs pull to make it work, now is running.

**Comment by Adibvafa** [comment]
Similar to https://github.com/microsoft/BiomedParse/issues/33

**Comment by FrancoisPorcher** [comment]
> > > [@FrancoisPorcher](https://github.com/FrancoisPorcher) Are you setting up a new conda enviornment for it?
> > 
> > 
> > Yes I am I just reproduced the environment from the authors (with mamba and not conda though)
> 
> You should follow the exact steps and setup a new conda environment otherwise you will run into issue.

Which command do you run though to execute `example_prediction.py` ?

**Comment by Adibvafa** [comment]
> > > > [@FrancoisPorcher](https://github.com/FrancoisPorcher) Are you setting up a new conda enviornment for it?
> > > 
> > > 
> > > Yes I am I just reproduced the environment from the authors (with mamba and not conda though)
> > 
> > 
> > You should follow the exact steps and setup a new conda environment otherwise you will run into issue.
> 
> Which command do you run though to execute `example_prediction.py` ?

just run it with python, should work.

**Comment by theodore-zhao** [comment]
Thanks for the answers in the thread! Yes, just python example_prediction.py should work. The error is likely to be the deprecated target_dist.json during git clone.

**Comment by jlgs96** [comment]
target_dist.json is in the git lfs format, you have yo use git lfs pull to get the correct format of the json and then execute the .py it worked to me.

**Comment by Adibvafa** [comment]
Would be nice to explain this in README

**Comment by theodore-zhao** [comment]
> Would be nice to explain this in README

Thanks for the suggestion. We have added this in README, and will refine the process in the near future.

**Comment by theodore-zhao** [comment]
We've now optimized the loading of target_dist.json to be independent of git. It directly downloads from huggingface when needed. Hope this can smooth the process.
