### ISSUE TITLE
Error during installing "pip install -r  assets/requirements/requirements.txt"

### ISSUE THREAD

**Issue by jlgs96** [microsoft/BiomedParse#34]
Hi there, first of all thank you so much for your work, im just creatig the conda environment as you explain but when i execute the command to install the dependencies, it throws me this error: ERROR: Failed to build installable wheels for some pyproject.toml based projects (mpi4py, detectron2)

What is the cause of this?

**Comment by franzmaliszt** [comment]
Same here, i am unable to create the environment, errorys mainly point to mpi4py. What about [commented dependencies in assets/requirements/requirements.txt](https://github.com/microsoft/BiomedParse/blob/6fa21ec7e4b3f37e227fa6e85760dd3db8a1258c/assets/requirements/requirements.txt#L35-L39)? 

I want to test if this model can run on cpu, but couldnt get it started. I'd appreciate any info on this as well.

**Comment by jlgs96** [comment]
i was able to install everything but separately and im not sure if it was the propper versions, but until the fix it i recommend doing it manually and adjusting versions. 

Warning: Keep tracking the CUDA version, most of the packages depends of it.

**Comment by perecanals** [comment]
Hi all, I am running into the same error as well. I have tried installing the mpi4py and the detectron2 packages individually, but I am stil running into installation errors in both instances. How did you exactly solve the problem @jlgs96  ?

Thank you,

**Comment by jlgs96** [comment]
Yeah, something like that, instead of what you did i see that the packages which create the problem were mpi4py and detectron2 and i installed manually, i got to update the CUDA toolkit and other things but it seems it worked.

**Comment by franzmaliszt** [comment]
@perecanals thanks a lot for this. i failed doing almost the same yesterday except for commenting `mpi4py` out in requirements.txt.

**Comment by macromeer** [comment]
I also needed to `sudo apt-get install libopenmpi-dev`

**Comment by theodore-zhao** [comment]
Thanks for the questions and answers in the thread! The match between pytorch and CUDA version is very important to make the environment work. If your machine has a different CUDA version, please install pytorch accordingly first. After that pip install the requirements.

**Comment by jlgs96** [comment]
Yeah, i just prepare the environment from zero and making all in order and worked at the end.

**Comment by WeisiX** [comment]
Are there any suggestions correctly installing detectron2? I tried installing it separately by running `python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'` but still getting `ERROR: Failed building wheel for detectron2`. I have gcc 8.5.0, g++ 8.5.0 and CUDA 12.3 (according to nvidia-smi). Pytorch 2.5.1 installed (compatible with CUDA 12.1).

**Comment by theodore-zhao** [comment]
> Are there any suggestions correctly installing detectron2? I tried installing it separately by running `python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'` but still getting `ERROR: Failed building wheel for detectron2`. I have gcc 8.5.0, g++ 8.5.0 and CUDA 12.3 (according to nvidia-smi). Pytorch 2.5.1 installed (compatible with CUDA 12.1).

Typically the issue with detectron2 installation is because of the mismatch between the CUDA version and pytorch version. From the torch website, maybe you can try pip3 install torch torchvision torchaudio or pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126 or pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 to see if any of these work?
