### ISSUE TITLE
The "background" position in the train_class_name

### ISSUE THREAD

**Issue by zhi-xuan-chen** [microsoft/BiomedParse#37]
Dear authors,

I noticed that you added the “background” category to the end of the train class names and used similarity calculations for classification. However, in your label ID definition, “background” is assigned as class 0. Could this potentially lead to some errors?

**Comment by theodore-zhao** [comment]
Thanks for noticing this detail! This actually doesn't affect the model's segmentation output. We took the same format as SEEM https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once in handling the class names.
