### ISSUE TITLE
With inference_examples_DICOM.ipynb, it hits: AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

### ISSUE THREAD

**Issue by liqunfu** [microsoft/BiomedParse#41]
Image.LINEAR is used at:
at https://github.com/MaureenZOU/detectron2-xyz/blob/42121d75e10d9f858f3a91b6a39f5722c02868f0/detectron2/data/transforms/transform.py#L46

it shall be Image.BILINEAR at:
https://github.com/facebookresearch/detectron2/blob/c69939aa85460e8135f40bce908a6cddaa73065f/detectron2/data/transforms/transform.py#L46

Shall https://github.com/MaureenZOU/detectron2-xyz sync with https://github.com/facebookresearch/detectron2 to get the fix:
https://github.com/facebookresearch/detectron2/commit/ff53992b1985b63bd3262b5a36167098e3dada02

I am using https://github.com/facebookresearch/detectron2 for now and the example works.

**Comment by theodore-zhao** [comment]
Thanks for the feedback! The two packages should produce the same model output. The xyz version was adapted from the original facebook version in SEEM, and we used that version for model development. For that reason we keep using this version for consistency. However, we also observed that sometimes one version works on some environment but not others. If the original facebook version works for you then please feel free to use it for your environment. If there is any change that causes continuous dependency problem we will consider changing to the facebook version.

**Comment by liqunfu** [comment]
Thanks. I am closing this issue because it is not a blocker.
