### ISSUE TITLE
Bounding Box creation

### ISSUE THREAD

**Issue by SSKlearns** [microsoft/BiomedParse#44]
Dear authors,

Thank you for your valuable contributions, and additionally releasing the code and weights.

We were attempting to generate bounding boxes, and we noticed that the "predict_name_matcher" and "predict_index_matcher" in https://github.com/microsoft/BiomedParse/blob/main/modeling/interface/prototype/attention_data_struct_seemdemo.py did not contain support for bounding boxes.

We did fix this on our end by adding the keys, however, the generated bounding boxes are in a different range, with some values being negative. Could you kindly guide us on your approach on converting these values to range of original image since we could not find a snippet that performed said operation.

Thank you.

**Comment by theodore-zhao** [comment]
Hi,

The current model wasn't trained to output bounding boxes, but if you have a segmentation mask, it is straightforward to take x_min, x_max, y_min and y_max to get the corresponding bounding box, depending on your purpose. Let me know if that's a solution works for you.

**Comment by SSKlearns** [comment]
Got it. Thank you so much! Since there was an option for detector within the configs, we considered the possibility of detection too. The bbox from segmentation masks should do the task for now.
